### ISSUE TITLE
Logging screen is leaking with not-GCed _LoggingScreenState in profile mode.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4416]
Follow https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/memory/panes/leaks/LEAK_TRACKING.md for DevTools with disabled inspector screen in profile mode connected to the counting app.

Navigate from page to page and resize screens till getting non-GCed leaks in console.

Connect another instance of DevTools to the first one to get the leaks:

```
not-gced:
  total: 4820
  culprits: 25
  victims: 4795
  objects:
    _LoggingScreenState:
      identityHashCode: 706266221
      retainingPath:
        - /Root-0
        - /Isolate-0
        - package:flutter/src/widgets/binding.dart/WidgetsFlutterBinding-785502347
        - package:flutter/src/widgets/framework.dart/BuildOwner-1134452307
        - dart.collection/_InternalLinkedHashMap-0
        - dart.core/_List-0
        - package:flutter/src/widgets/framework.dart/StatefulElement-89914675
        - package:flutter/src/widgets/navigator.dart/NavigatorState-287530411
        - dart.core/_GrowableList-0
        - dart.core/_List-0
        - package:flutter/src/widgets/navigator.dart/_RouteEntry-466314405
        - package:flutter/src/material/dialog.dart/DialogRoute-3140187413
        - dart.core/_Closure-1712828922
        - /Context-797029043
        - dart.core/_Closure-4001193036
        - /Context-3533831527
        - package:devtools_app/src/screens/logging/logging_screen.dart/_LoggingScreenState-706266221
      total-victims: 4771
```
