### ISSUE TITLE
When you start DevTools, Network can't listen to network requests

### ISSUE THREAD

**Issue by laterdayi** [flutter/devtools#8010]
When you start DevTools, Network can't listen to network requests

https://github.com/flutter/devtools/assets/122137647/34d8dbdc-deda-40e9-abc5-95a46b29a8db

InternetAddress is always displayed with no network requests

![image](https://github.com/flutter/devtools/assets/122137647/b885a568-adb0-45fc-9cf4-b26cc1c2fa47)

```

version: 1.0.41+41

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  bot_toast: ^4.1.3
  get: ^4.6.6
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  easy_refresh: ^3.3.5
  package_info_plus: ^7.0.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  logger: ^2.2.0
  open_filex: ^4.4.0
  android_id: ^0.3.6
  barcode_widget: ^2.0.4
  device_info_plus: ^10.1.0
  jiffy: ^6.2.1
  camera: ^0.10.5+9
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  pubspec_manager: ^1.0.0
```

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.19045.2965], locale zh-CN)
    ! Warning: `flutter` on your path resolves to E:\flutter\versions\stable\bin\flutter, which is not inside your
      current Flutter SDK checkout at E:\flutter\default. Consider adding E:\flutter\default\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to E:\flutter\versions\stable\bin\dart, which is not inside your current
      Flutter SDK checkout at E:\flutter\default. Consider adding E:\flutter\default\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
[√] Android Studio (version 2024.1)
[√] Connected device (4 available)
[!] Network resources
    X A network error occurred while checking "https://maven.google.com/"


! Doctor found issues in 2 categories.
```
