### ISSUE TITLE
Disable two finger scroll back gesture

### ISSUE THREAD

**Issue by knopp** [flutter/devtools#8661]
Right now horizontal scrolling can get quite frustrating because two scroll triggers back gesture in chrome. The fix is rather straightforward, adding `overscroll-behavior-x: none` style to `body`, i.e.

```css
body {
  overscroll-behavior-x: none;
}
```      

https://github.com/user-attachments/assets/88741bf9-d4f4-4557-9f1d-bce69fc5a99f
